# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags: [ 'app.command_handler' ]

        App\Order\Domain\Calculator\Operations\Operation:
            tags: [ 'app.operation' ]
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Order\Domain\Product\Factory\ProductFactory:
        arguments:
            $products:
                - '@App\Order\Domain\Product\Pizza'
                - '@App\Order\Domain\Product\Burger'
                - '@App\Order\Domain\Product\Sushi'

    App\Order\Domain\Calculator\CalculateAmount:
        arguments: [ !tagged app.operation ]

    ### Buses
    App\Shared\Infrastructure\Bus\Command\InMemoryCommandBus:
        arguments: [ !tagged app.command_handler ]